#ifndef CONFIG_H
#define CONFIG_H
#pragma once

#define OUTPUT_PIN 27
#define OUTPUT_FREQUENCY 200
#define OUTPUT_RESOLUTION 8
#define OUTPUT_CHANNEL 1
#define RESISTANCE 0.22

#define BUTTON_PIN 13
#define BUTTON_GPIO GPIO_NUM_13

#define BATTERY_PIN 34
#define ADC_CONV_FACTOR 1.7

#define DISPLAY_LIGHT_TIMEOUT 3000
#define DISPLAY_DEEP_TIMEOUT 6000
#define DISPLAY_LIGHT_BRIGHTNESS 1
#define DISPLAY_NORMAL_BRIGHTNESS 100

#endif